[project]
name = "tinygsviewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "glfw>=2.10.0",
    "imageio>=2.37.2",
    "imgui>=2.0.0",
    "numpy>=2.4.0",
    "plyfile>=1.1.3",
    "pyglm>=2.8.3",
    "pyopengl>=3.1.10",
    "torch>=2.9.1",
]
